version: '2'
services:

  bubuku:
    build: .
    depends_on:
      - zookeeper
    environment:
      BUBUKU_MODE: "local"
      HEALTH_PORT: "8080"
      BUKU_FEATURES: "restart_on_exhibitor,rebalance_on_brokers_change,graceful_terminate"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  zookeeper-ui:
    image: elkozmon/zoonavigator:latest
    environment:
      HTTP_PORT: 9000
    ports:
      - "8081:9000"
